### PR TITLE
Gulp version of our project

### PR DESCRIPTION
**Pull request by bwalowitz**

### CODE REVIEW

**Comment by bwalowitz** [comment]
@riklomas Can you let me know what the conflict is? I tried to resolve it on the command line, but it didn't work. Thanks!

**Comment by riklomas** [comment]
Try doing `git rm app.css` in the command line and see if that helps?

**Comment by bwalowitz** [comment]
@riklomas I did that and it returned: fatal: pathspec 'app.css' did not match any files

**Comment by riklomas** [comment]
I just deleted the app.css on master just to stop it complaining!

**Comment by bwalowitz** [comment]
What a complainer! Thanks!

**Pull request merged**
